language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t aquintero446/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aquintero446/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-andres"
  env: "DockerReactAndres-env"
  bucket_name: "elasticbeanstalk-us-east-2-774154012305"
  bucket_path: "docker-react-andres"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
